### ISSUE TITLE
系统找不到指定的路径。……之不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by DIIIIIICKY** [thanksshu/UTCNetGo-Win#1]
C:\Users\liuch\Desktop\UTCNetGo-Win-master>cmd /c core\main.start.bat
系统找不到指定的路径。
'orlevel' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'RequestUAC.ShellExecute' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'请求管理员权限' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'3' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'tokens' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'择' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'0%"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'metric' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'0%"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'd' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'：停止' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'?结束' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'hisdown' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'操作中' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'.....0%"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'/IM' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'%"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'/IM' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'%"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'.0.0' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'%"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'.0.0.0' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'%"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'proxygateway' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'0%"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'完成' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'es_sig' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'rt' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'oto' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'崾?' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'糁?start' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'er' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'任意键退出' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by thanksshu** [comment]
基本是找不到路径的锅，先运行一下这个试一下。
[cacls.test.bat.zip](https://github.com/thanksshu/UTCNetGo-Win/files/2870792/cacls.test.bat.zip)

**Comment by DIIIIIICKY** [comment]
C:\Users\liuch\Desktop\UTCNetGo-Win-master>cd /d "C:\Users\liuch\Desktop\UTCNetGo-Win-master\"

C:\Users\liuch\Desktop\UTCNetGo-Win-master>cacls.exe "C:\System Volume Information"  1>nul 2>nul

C:\Users\liuch\Desktop\UTCNetGo-Win-master>if 5 == 0 echo Done

C:\Users\liuch\Desktop\UTCNetGo-Win-master>pause
请按任意键继续. . .

**Comment by thanksshu** [comment]
排除“%~dp0”和"%SystemDrive%\System Volume Information"的问题，
再测试另外一个：
[temp.test.bat.zip](https://github.com/thanksshu/UTCNetGo-Win/files/2870846/temp.test.bat.zip)

**Comment by DIIIIIICKY** [comment]
C:\Users\liuch\Desktop>if exist "C:\Users\liuch\AppData\Local\Temp\getadmin.vbs" del /f /q "C:\Users\liuch\AppData\Local\Temp\getadmin.vbs"

C:\Users\liuch\Desktop>echo Set RequestUAC = CreateObject("Shell.Application") 1>"C:\Users\liuch\AppData\Local\Temp\getadmin.vbs"

C:\Users\liuch\Desktop>echo RequestUAC.ShellExecute "C:\Users\liuch\Desktop\TEMPTE~1.BAT","/k","","runas",1  1>>"C:\Users\liuch\AppData\Local\Temp\getadmin.vbs"

C:\Users\liuch\Desktop>echo WScript.Quit  1>>"C:\Users\liuch\AppData\Local\Temp\getadmin.vbs"

C:\Users\liuch\Desktop>if exist "C:\Users\liuch\AppData\Local\Temp\getadmin.vbs" del /f /q "C:\Users\liuch\AppData\Local\Temp\getadmin.vbs"

C:\Users\liuch\Desktop>pause
请按任意键继续. . .

**Comment by thanksshu** [comment]
已解决，请按说明下载并使用。
