### ISSUE TITLE
启动成功但是依旧无法访问

### ISSUE THREAD

**Issue by thanksshu** [thanksshu/UTCNetGo-Win#2]
;请先完善标题！

**Bug描述**
启动成功未显示异常，但是依旧无法访问原先不能访问的地址。

**重现步骤**
填写如何重现Bug:
1. 配置config.ini，gateway项改为172.29.16.1
2. 启动并没有出现异常
3. 依旧无法访问

**理想预期**
能够访问原不能访问的地址

**截图**
暂无

**桌面设备 (完成下列信息):**
 - OS: Windows
 - 浏览器: [e.g. Chrome, Firefox]
 - 系统版本: [e.g.企业版 1803 64位]
 - 浏览器版本: [e.g.65.0.1 (64 位)]

**额外信息**
填写额外信息

**Comment by thanksshu** [comment]
测试路由，把运行后的截图发一下，记得隐私处理。
[route.print.4.bat.zip](https://github.com/thanksshu/UTCNetGo-Win/files/2872986/route.print.4.bat.zip)

**Comment by suzaku-et-lancelot** [comment]
![qq 20190217213418](https://user-images.githubusercontent.com/47715042/52913724-e44de100-32fb-11e9-8e69-5872f4619cc9.png)

**Comment by thanksshu** [comment]
嗯……有两个问题:
有一个神奇的网关，需要进一步调查。
Tap网卡启动不成功，老问题了，正在修复，现在可以先重启脚本（按“R”）。

**Comment by suzaku-et-lancelot** [comment]
![111](https://user-images.githubusercontent.com/47715042/52913951-dac57880-32fd-11e9-9c7b-498103a134ad.png)

**Comment by thanksshu** [comment]
安装好TAP网卡了吗？如果安装好了，那这就是比较严重的问题了。
检查安装，去电脑的“控制面板\网络和 Internet\网络连接”，截图给我一下，记得隐私处理。

**Comment by suzaku-et-lancelot** [comment]
![image](https://user-images.githubusercontent.com/47715042/52914061-d188db80-32fe-11e9-8247-587d71a791ec.png)

**Comment by thanksshu** [comment]
……不是直接访问啦，这是控制面板的一个路径，在“控制面板\网络和 Internet\网络和共享中心”点击”更改适配器选项“就可以了，是我描述得不好。

**Comment by suzaku-et-lancelot** [comment]
![image](https://user-images.githubusercontent.com/47715042/52914137-af438d80-32ff-11e9-85fa-4091cc2db145.png)

**Comment by thanksshu** [comment]
忘记安装TAP网卡了吧？回到说明里找到安装TAP-Windows一下再试试？

**Comment by thanksshu** [comment]
已解决啊……Tap网卡一定要装。
